# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version. Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
 
  # Vagrant Box
  config.vm.box = "chad-thompson/ubuntu-trusty64-gui"
  
  # Vagrant provider settings	
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "Anson-prdesai2-Evoss"
    vb.memory = "1024"
    #Disable USB
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
  
  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
  
	 # Install Java
	 sudo add-apt-repository ppa:webupd8team/java
	 sudo apt-get update
	 echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
	 sudo apt-get install -y oracle-java8-installer
	 
	 # Install git utility
 	 sudo apt-get install -y git
	 
	 #Adobe Flash player required in order to view the YouTube video
         sudo apt-get install flashplugin-installer
	
	 # Download the Evoss file
	 wget https://mancoosi-uda.googlecode.com/files/all-evoss.tar.gz -O /home/vagrant/Desktop/all-evoss.tar.gz
	 
	 # Create a folder in home directory
	 mkdir -p /home/mancoosi/mancoosi
	 
	 # Copy evoss to this new folder
	 sudo scp /home/vagrant/Desktop/all-evoss.tar.gz /home/mancoosi/mancoosi/evoss.tar.gz
	 cd /home/mancoosi/mancoosi
	 
	 # Extract the tar
	 tar -xvzf evoss.tar.gz
	 
	 # Install libupnp6
	 sudo apt-get install libupnp6
	 
	 cd /home/mancoosi/mancoosi/evoss
	 cd modelInjectors/cfginject
	 java -jar cfginject.jar 
	 java -jar cfginject.jar
	 cd ../pkginject
	 java -jar pkginject.jar -p libupnp6 1:1.6.17-1.2 amd64
	 
	 # clone items to desktop
	 git clone https://github.com/SoftwareEngineeringToolDemos/ICSE-2012-EVOSS.git /home/vagrant/Desktop/ICSE-2012-EVOSS
	 sudo chmod a+rwx /home/vagrant/Desktop/ICSE-2012-EVOSS
	 sudo mv /home/vagrant/Desktop/ICSE-2012-EVOSS/build-vm/vm-contents/* /home/vagrant/Desktop/

	 #In order to open the terminal on boot, place the .desktop file in the ~/.config folder
      	 cd /home/vagrant/.config
      	 mkdir autostart
      	 cd autostart
      	 touch gnome-terminal.desktop
      	 printf "[Desktop Entry]\n Type=Application\n Name=Terminal\n Exec=gnome-terminal \nNoDisplay=false" >> gnome-terminal.desktop
		 
	 #Disable the screen-lock
         sudo wget https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-EVOSS/master/build-vm/vm-contents/DisableLock.desktop
         sudo chmod 777 /home/vagrant/.config/autostart/DisableLock.desktop
	  
	 # Open the terminal at the correct location- "/home/mancoosi/mancoosi/evoss/simulator"
      	 printf "cd /home/mancoosi/mancoosi/evoss/simulator" >> /home/vagrant/.bashrc
      	 printf "\n echo *****Commandline Interface for Evoss*****" >> /home/vagrant/.bashrc
      
	 # Remove extra applications from the launcher
      	 sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
      	 sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
	  
	 #Reboot the system
      	 sudo reboot
	  
   SHELL
end
